# Generated by Django 2.2.4 on 2023-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='comm',
            field=models.ManyToManyField(related_name='course_comm', to='courses_app.Comment'),
        ),
    ]
