# Generated by Django 2.2.4 on 2023-06-23 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='exam_app.User'),
            preserve_default=False,
        ),
    ]
