# Generated by Django 2.2.4 on 2023-06-23 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_team_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='skill_level',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
