# Generated by Django 2.2.4 on 2023-06-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_auto_20230623_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
